# Generated by Django 4.2.7 on 2023-11-07 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmranAhmadi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField(default=0)),
                ('inch', models.CharField(max_length=10)),
                ('wieght', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pips_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SellPip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('totalprice', models.FloatField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmranAhmadi.bill')),
                ('pip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmranAhmadi.pip')),
            ],
        ),
        migrations.AddField(
            model_name='pip',
            name='piptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmranAhmadi.pips_type'),
        ),
        migrations.CreateModel(
            name='BuyMatrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wieght', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('company', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('piptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmranAhmadi.pips_type')),
            ],
        ),
    ]
