# Generated by Django 4.2.7 on 2023-12-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmranAhmadi', '0002_bill_pip_pips_type_sellpip_pip_piptype_buymatrial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
